name: CI

on:
  push:
    branches: [ master ]

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build svgnest package
        run: nix build .

      - name: Upload svgnest artifact
        uses: actions/upload-artifact@v4
        with:
          name: svgnest-package
          path: result/
      
      - name: Setup node for publishing
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to npm
        working-directory: result/
        run: npm publish

      - name: Build demo
        run: |
          nix develop --command bash -c "cd demo && npm install && npm run build"

      - name: Upload demo artifact
        uses: actions/upload-artifact@v4
        with:
          name: demo-dist
          path: demo/dist/

      - name: Deploy on GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          folder: demo/dist/
          token: ${{ secrets.DEPLOY_TOKEN }}
          repository-name: zopieux/zopieux.github.io
          branch: master
          target-folder: svgnest
          commit-message: Deploy svgnest demo.
          git-config-user: Alexandre Macabies
          git-config-email: <web+oss@zopieux.com>
